---
server:
  port: 8888 
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/toddisaacs/springcloud-config
          #username:
          #password:
          search-paths:
          - 'station*'
          repos:
            perf:
              pattern:
              - '*/perf'
              uri: https://github.com/toddisaacs/springcloud-config-perf
              search-paths:
                - 'station*'
          